
name: Release
on: workflow_dispatch

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache Rust Toolchain and Linker
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            /usr/bin/x86_64-w64-mingw32-gcc
            /usr/lib/gcc/x86_64-w64-mingw32
            /usr/x86_64-w64-mingw32/lib
            /usr/x86_64-w64-mingw32/include
            ~/.rustup/toolchains/*-x86_64-pc-windows-gnu
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          save-always: true

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install mingw-w64 linker
        run: sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Set Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Compile
        run: cargo build --release --target ${{ matrix.target }}

      - name: Archive Folder
        uses: vimtor/action-zip@v1
        with:
          files: README.md LICENSE install.bat target/${{ matrix.target }}/release/itch-io-downloader.exe addon/
          recursive: false
          dest: itch-io-downloader-${{ matrix.target }}.zip

      - name: Upload to Latest Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "itch-io-downloader-${{ matrix.target }}.zip"
          update_latest_release: true
          overwrite: true
