
name: Release
on: workflow_dispatch

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      matrix:
        target: [ x86_64-pc-windows-gnu ]
        linker_bin: [ x86_64-w64-mingw32-gcc ]
        linker_lib: [ x86_64-w64-mingw32 ]
        linker_package: [ gcc-mingw-w64-x86-64 ]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache Rust Toolchain and Linker
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            /usr/bin/${{ matrix.linker_bin }}
            /usr/lib/gcc/${{ matrix.linker_lib }}
            /usr/${{ matrix.linker_lib }}/lib
            /usr/${{ matrix.linker_lib }}/include
            ~/.rustup/toolchains
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          save-always: true

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install mingw-w64 linker
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo apt-get install -y ${{ matrix.linker_package }}

      - name: Install Rust Target
        if: steps.cache.outputs.cache-hit != 'true'
        run: rustup target add ${{ matrix.target }}

      - name: Compile
        run: cargo build --release --target ${{ matrix.target }}

      - name: Move Compiled Executable
        run: cp ./target/${{ matrix.target }}/release/itch-io-downloader.exe ./itch-io-downloader.exe

      - name: Add itch-io-downloader.json Placeholder
        run: cp ./itch-io-downloader.json.placeholder ./itch-io-downloader.json

      - name: Archive Folder
        uses: vimtor/action-zip@v1
        with:
          files: README.md LICENSE install.bat itch-io-downloader.exe itch-io-downloader.json addon/
          recursive: false
          dest: itch-io-downloader-${{ matrix.target }}.zip

      - name: Upload to Latest Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "itch-io-downloader-${{ matrix.target }}.zip"
          update_latest_release: true
          overwrite: true
