
name: Release
on: workflow_dispatch

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache Rust Toolchain and Linker
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            /usr/bin/x86_64-w64-mingw32-gcc
            /usr/lib/gcc/x86_64-w64-mingw32
            /usr/x86_64-w64-mingw32/lib
            /usr/x86_64-w64-mingw32/include
            ~/.rustup/toolchains/*-x86_64-pc-windows-gnu
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install mingw-w64 linker
        run: sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Set Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Compile
        run: cargo build --release --target ${{ matrix.target }}

      - name: Archive Folder
        uses: vimtor/action-zip@v1
        with:
          files: README.md LICENSE install.bat target/release/itch-io-downloader.exe addon/
          recursive: false
          dest: itch-io-downloader-x86_64-windows.zip

      - name: Get Last Release URL
        id: get_last_release
        run: |
            url=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases | jq '.latest.upload_url' | tr -d '"')
            echo "Last release URL: $url"
            echo "::set-output name=last_release_url::$url"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_last_release.outputs.last_release_url }}
          asset_path: ./itch-io-downloader-${{ matrix.target }}.zip
          asset_name: itch-io-downloader-${{ matrix.target }}.zip
          asset_content_type: application/zip
